### ISSUE TITLE
When opening the app library on a workspace with no open windows, I have to hit Esc twice to close the app library

### ISSUE THREAD

**Issue by leviport** [pop-os/cosmic-applibrary#10]
### Summary:
Closing the app library with Esc takes a double Esc press to close it if I open the app library on a workspace with no open windows. If I have a browser window open and open the app library over the top of it, a single Esc press is enough to close it.

### Steps to reproduce:
- Switch to a workspace with no open windows
- Open the app library with Super + A
- Hit Esc once, app library should not close
- Hit Esc again, app library should close after the second press

### Expected behavior:
It should probably close after a single Esc press, like it does when I open it on a workspace with a window open.

### Version:
```
$ apt policy cosmic-app-library 
cosmic-app-library:
  Installed: 0.1.0~1660784434~22.04~dc85e14
  Candidate: 0.1.0~1660784434~22.04~dc85e14
  Version table:
 *** 0.1.0~1660784434~22.04~dc85e14 1002
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1002 http://apt.pop-os.org/staging/master jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by leviport** [comment]
Oh it seems like it can happen with certain applications open as well. Single Esc works nicely on a workspace with a Firefox window open, but it needs a double Esc on a workspace with Gnome Terminal or LibreOffice windows open.

**Comment by leviport** [comment]
Ah, the second keypress doesn't even need to be Esc, it can by any key. So Esc then spacebar, or Esc then B, will close the app library. I'm also seeing the same thing happen with the launcher, so this might be more of a general COSMIC bug rather than one specific to the app library.

**Comment by wash2** [comment]
Ya this is probably more an issue with https://github.com/pop-os/cosmic-applet-host

**Comment by Drakulix** [comment]
> Ah, the second keypress doesn't even need to be Esc, it can by any key. So Esc then spacebar, or Esc then B, will close the app library. I'm also seeing the same thing happen with the launcher, so this might be more of a general COSMIC bug rather than one specific to the app library.

Sounds like it is missing a re-render?
Could also be cosmic-comp not realizing the layer-shell surface is gone. :thinking:

**Comment by leviport** [comment]
>Sounds like it is missing a re-render?

Yeah that sounds pretty likely. I've seen other occurrences of what look like missing re-renders, but they're quite a bit harder to reproduce reliably. The one I see the most often is when I open a new terminal with Super+T on an empty workspace. Sometimes it doesn't appear until I press another key. I'll report back if I find a way to make it happen more reliably.

**Comment by wash2** [comment]
> Could also be cosmic-comp not realizing the layer-shell surface is gone. thinking

Ya at the point after I've destroyed the surface, I probably can't do another render, right? I can recreate this issue, but ya it's weird that the surface only disappears after some additional key press or mouse movement.

**Comment by leviport** [comment]
Looks like this is fixed now
