### ISSUE TITLE
Closing the app library without launching anything doesn't fully return focus to the previously active window

### ISSUE THREAD

**Issue by leviport** [pop-os/cosmic-applibrary#11]
### Summary:
If I open the app library over the top of an application, say, Gnome Terminal or LibreOffice Writer, then I close the app library with the Esc key, I need to click the application window with my mouse before I can resume typing in that application.

### Steps to reproduce:
- Open LibreOffice Writer and type a bit
- Open the app library with Super + A
- Close the app library with Esc (might take a double press due to #10)
- Try to continue typing in Writer, it shouldn't work

### Expected behavior:
After closing the app library with Esc, I'd expect to be able to resume typing in Writer without having to click it with my mouse.

### Version:
```
$ apt policy cosmic-app-library 
cosmic-app-library:
  Installed: 0.1.0~1660784434~22.04~dc85e14
  Candidate: 0.1.0~1660784434~22.04~dc85e14
  Version table:
 *** 0.1.0~1660784434~22.04~dc85e14 1002
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1002 http://apt.pop-os.org/staging/master jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by wash2** [comment]
I think this issue probably should be on either
https://github.com/pop-os/cosmic-applet-host
or
https://github.com/pop-os/cosmic-comp

**Comment by Drakulix** [comment]
This might be related to https://github.com/pop-os/cosmic-applibrary/issues/12.

@wash2 Can you confirm that the applet-host destroys the surface correctly?
If it does, this is clearly a cosmic-comp bug.

**Comment by wash2** [comment]
> This might be related to #12.
> 
> @wash2 Can you confirm that the applet-host destroys the surface correctly? If it does, this is clearly a cosmic-comp bug.

```rust
fn drop(&mut self) {
    self.layer_surface.destroy();
}
```
    
This is the drop function for when an active applet is removed.

**Comment by leviport** [comment]
This looks like it got fixed too
