### ISSUE TITLE
No way to add apps to groups

### ISSUE THREAD

**Issue by leviport** [pop-os/cosmic-applibrary#12]
### Summary: 
I can't find a way to add applications to different groups. Clicking and dragging doesn't work, and I don't get right click context menus within the app library when I right click on stuff.

### Steps to reproduce:
- With the app library open, try clicking and dragging icons into different groups

### Expected behavior:
Clicking and dragging apps into different groups seems like the most obvious thing users would try in order to add apps to a group.

### Version:
```
$ apt policy cosmic-app-library 
cosmic-app-library:
  Installed: 0.1.0~1660784434~22.04~dc85e14
  Candidate: 0.1.0~1660784434~22.04~dc85e14
  Version table:
 *** 0.1.0~1660784434~22.04~dc85e14 1002
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1002 http://apt.pop-os.org/staging/master jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by wash2** [comment]
Thanks, applet host doesn't support DnD quite yet since the 0.30 refactors, but I'll work on DnD and then add support for adding applications to new groups.

**Comment by jacobgkau** [comment]
Clicking and dragging apps over different folder icons now moves the apps into/between those folders.

Opened a related issue about Library Home still containing the icon after adding it to a folder: https://github.com/pop-os/cosmic-applibrary/issues/69
