### ISSUE TITLE
Newly created groups contain all apps from "Library Home"

### ISSUE THREAD

**Issue by leviport** [pop-os/cosmic-applibrary#13]
### Summary:
If I create a new group, it has all of my applications in it. I feel like this might be a placeholder until customizing groups is better supported (#12), but this still seemed like it was worth putting on the list.

### Steps to reproduce:
- With the app library open, create a new group by clicking the "New Group" button (it might need a double click: #8)
- Give it a name and click "Ok"
- The newly created group should contain all applications in the library

### Expected behavior:
The new group should start out empty, then the user should be able to add applications to it.

### Version:
```
$ apt policy cosmic-app-library 
cosmic-app-library:
  Installed: 0.1.0~1660784434~22.04~dc85e14
  Candidate: 0.1.0~1660784434~22.04~dc85e14
  Version table:
 *** 0.1.0~1660784434~22.04~dc85e14 1002
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1002 http://apt.pop-os.org/staging/master jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by wash2** [comment]
Ok, this should be fixed :) by 3480c88611958c0c32d03d6debbeb0d246bc7a36

**Comment by n3m0-22** [comment]
New groups start empty now, but I can't seem too add any apps to them. Is that not supported yet?

**Comment by wash2** [comment]
> New groups start empty now, but I can't seem too add any apps to them. Is that not supported yet?

ya it is not supported yet

**Comment by n3m0-22** [comment]
This is fixed.
