### ISSUE TITLE
"New Group" dialog's button styling looks a little off

### ISSUE THREAD

**Issue by leviport** [pop-os/cosmic-applibrary#14]
### Summary: 
The "Ok" and "Cancel" buttons on the "New Group" dialog are aligned to the left, and it looks like there is a darker gray bar below them which sticks off on the right side. I'd take a screenshot, but it looks like none of my screenshot utilities seem to be working in COSMIC quite yet :sweat_smile: 

### Steps to reproduce:
- Open app library
- Double click "New Group"

### Expected behavior:
The darker gray bar beneath the buttons probably shouldn't be there, and the "Cancel" button should probably be aligned to the right side of the dialog. Keeping the "Ok" button left-aligned is probably what we want.

### Version:
```
$ apt policy cosmic-app-library 
cosmic-app-library:
  Installed: 0.1.0~1660784434~22.04~dc85e14
  Candidate: 0.1.0~1660784434~22.04~dc85e14
  Version table:
 *** 0.1.0~1660784434~22.04~dc85e14 1002
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1002 http://apt.pop-os.org/staging/master jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by n3m0-22** [comment]
This is fixed.

Before:

![before](https://user-images.githubusercontent.com/11048214/187247101-215b4a81-0043-45aa-9591-14f256da0de1.jpg)

After:

![after](https://user-images.githubusercontent.com/11048214/187247163-fe9ce054-54a7-4714-a749-aa7cb049edd9.jpg)
