### ISSUE TITLE
App Library Styling details

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/cosmic-applibrary#15]
Below are details about the styling adjustments for the padding and spacing for the COSMIC App Library. 

### Dark Appearance Mockups
![AppLibrary-home-dark](https://user-images.githubusercontent.com/57502897/188935680-446c0845-44bb-4e37-88eb-43ae98918623.png)
![AppLibrary-folder-dark](https://user-images.githubusercontent.com/57502897/188935494-506046ab-0815-4dd6-9e98-a465c2e030ee.png)

### Light Appearance Mockups
![AppLibrary-home-light](https://user-images.githubusercontent.com/57502897/188935610-3eec33d4-1244-4558-963a-58796a621d18.png)
![AppLibrary-folder-light](https://user-images.githubusercontent.com/57502897/188935589-85d18e43-0e46-4802-b36f-45ed1931b57f.png)

### App icon and folder icon states
![icon-states](https://user-images.githubusercontent.com/57502897/188936027-86802955-2650-4f08-96f3-dad217b48e45.png)

### Padding and spacing
![folder-icon](https://user-images.githubusercontent.com/57502897/188936121-b3c7c92f-6305-44d9-84e2-c5eb72b446a6.png)
![app-icon](https://user-images.githubusercontent.com/57502897/188936176-0b7efdf1-1417-4a8f-8a9e-a46d735bca29.png)

### Padding
![padding](https://user-images.githubusercontent.com/57502897/188935877-026bd041-3a99-4163-92ce-20c98e99a1fd.png)

Additional information about color variables can be found in Figma: https://www.figma.com/file/fisG9pTBNlHrzT5yyPgTog/Applications-Library?node-id=10%3A565

**Comment by wash2** [comment]
Ok thanks! I'll make the adjustments +1

**Comment by wash2** [comment]
Ok, I'm nearly done with the changes for this :). Just a couple questions for now.

Should the spacing between folder grid rows be the same as for app grid rows? 

Should "Library Home" be the only folder that can be searched?

**Comment by wash2** [comment]
Ok, currently the view that the folder icons are in will turn into a scrollable view after there are more than two rows. I'm open to trying another approach like shrinking the icons though.

**Comment by maria-komarova** [comment]
I wonder if shrinking might be a bit better so that we don't stack two scrollable areas.
