### ISSUE TITLE
sometimes application menu doesn't show

### ISSUE THREAD

**Issue by bingmatv** [pop-os/cosmic-applibrary#183]

**Comment by leviport** [comment]
Bug reports need more information than this to be helpful. What distro? How are you attempting to summon the app library? Does another way work better?

**Comment by bingmatv** [comment]
On ArchLinux, unsure how to reproduce the bug.

**Comment by leviport** [comment]
If you can't provide more details, we can't really know enough about what you're seeing in order to do something about it. I can reopen this issue if you can flesh out a more complete bug report.
