### ISSUE TITLE
gnome-cosmic to cosmic-applibrary comparison

### ISSUE THREAD

**Issue by n3m0-22** [pop-os/cosmic-applibrary#32]
|Feature List                               |gnome-cosmic|cosmic-applibrary|Issues                                               |
|-------------------------------------------|------------|-----------------|-----------------------------------------------------|
|launch with `Super` + `a`                      |working     |working          |                                                     |
|create folder                              |working     |working          |                                                     |
|always opens to library home               |working     |working      |fixed by https://github.com/pop-os/cosmic-applibrary/pull/33                                       |
|search then close opens back to home       |working     |working      |fixed by https://github.com/pop-os/cosmic-applibrary/pull/33|
|search also searches for `Available to Install`|working     |not working      |                                                     |
|open/close with 4 finger swipe             |working     |not working      |                                                     |
|scrolling                                  |working     |working          |                                                     |
|drag/move apps between sections                                  |working     |not working          | Only works in one direction  |
|menu on app icon right click                                  |working     |working          |                                                     |
|apps only show in one section                                  |working     |working          |                                                     |
|apps are sorted into default sections                                  |working     |working          |                                                     |
|use `Tab` to navigate library                                  |working     |not working          |    Doesn't scroll view when navigating with keyboard     |

**Comment by wash2** [comment]
> always opens to library home, search then close opens back to home

should be fixed by https://github.com/pop-os/cosmic-applibrary/pull/33

**Comment by n3m0-22** [comment]
Updated to reflect the most recent changes. Getting closer!

**Comment by senntore** [comment]
I'm not sure if it's intended but in Cosmic, there is increase in height of the application library when we navigate to folders other than library home.
I like how application library in Pop OS 22.04 has consistent height.

**Comment by jacobgkau** [comment]
I don't think it's intentional for the height to be different.

**Comment by senntore** [comment]
I also saw that the folders/groups in Cosmic are not sorted alphabetically like they do in current Pop OS. You might want to add that to the list.
