### ISSUE TITLE
context menu: toggle stops working

### ISSUE THREAD

**Issue by cmeissl** [pop-os/cosmic-applibrary#45]
Using the context menu to launch an app using a sub entry like `Open Profile Manager` for `Firefox` seems to break the app library. After selecting such an entry the app library can no longer be toggled. Selecting `Run` or directly launching the app without the context menu does not show this symptom.

**Comment by wash2** [comment]
Ahh thanks, I'll look into this

**Comment by jacobgkau** [comment]
Still seeing this on de313ec.
