### ISSUE TITLE
Apps in folders also show up in Library Home

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-applibrary#69]
Currently, dragging an icon from Library Home into a folder does add the icon to that folder, but the icon still remains in Library Home. Additionally, apps that are in folders by default (like the LibreOffice icons in the Office folder) still show up in Library Home.

To match the old COSMIC as well as the Figma mockups, apps that are in a folder should not show up in Library Home. Library Home is simply a fallback folder for icons that aren't in any other folders, not an overview of all apps.

**Comment by wash2** [comment]
Ok, that sorta has to do with https://github.com/pop-os/cosmic-applibrary/issues/49

I can make it show just the apps not in another group for the home folder when the search field is empty, and otherwise search all apps?

**Comment by jacobgkau** [comment]
> I can make it show just the apps not in another group for the home folder when the search field is empty, and otherwise search all apps?

Yes, that's the behavior in old COSMIC and seems to still be what UX had in mind.
