### ISSUE TITLE
[ Feature request ] Add the option to use an icon

### ISSUE THREAD

**Issue by ryzendew** [pop-os/cosmic-applibrary#75]
instead of words give us the option to have no words but an icon instead like a start menu and the ability to change out that icon like with arcmenu

**Comment by git-f0x** [comment]
This has been added (it uses an icon on a panel at M or larger, and always on the dock). There's a config option to force it to always use an icon. It' also planned to add applet configuration in Settings (including selecting if the button should be and icon or text), so this can probably be closed.

**Comment by WatchMkr** [comment]
Tracking this here: https://github.com/pop-os/cosmic-applets/issues/462
