### ISSUE TITLE
"Remove" context option doesn't work

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-applibrary#85]
Right-clicking any icon in any folder opens a menu with "Remove" as one of the options. That option doesn't seem to do anything.

I'm assuming this menu item should move an icon back to Library Home if it's in another folder. (I don't think it should show up if it's in Library Home.) May need clarification from @pop-os/ux if it's supposed to do something else, as it wasn't present in GNOME COSMIC.

**Comment by wash2** [comment]
It works for custom groups, but ya, I believe it shouldn't show on the home page. I'll look into why it's not working for the built in Office / System / Utilities groups.

**Comment by wash2** [comment]
This should be fixed by #86
