### ISSUE TITLE
200% scaling has scroll bar for home page

### ISSUE THREAD

**Issue by ryanabx** [pop-os/cosmic-applibrary#89]
![screenshot-2024-03-07-19-37-00](https://github.com/pop-os/cosmic-applibrary/assets/56272643/ff65ec4a-8b60-4d9d-bf08-cf5d327c4c17)

Not sure if this is intended or not, let me know.

This is a 16x10 1600p display at 200% scaling

**Comment by jacobgkau** [comment]
Confirmed on a bonw15 with a 1440p display that this is also fixed for 200% configurations.
