### ISSUE TITLE
app activation requires a mouse press, enter/return keyboard press has no effect

### ISSUE THREAD

**Issue by jokeyrhyme** [pop-os/cosmic-applibrary#95]
Howdie,

I noticed that I can type a few letters to filter apps, and then tab and arrow-key around to move some sort of highlight/focus outline around to the app I want, but pressing enter/return does not launch the app

Looking at the code, I think it's because only the press event on the button widget is wired up, but I would have thought that would include enter/return (and even space?): https://github.com/pop-os/cosmic-applibrary/blob/8df76d5d228759136156f5cd1fd728b1df956475/src/app.rs#L945

Is this the intended behaviour?

If you're okay with me raising a PR to fix this, is this likely to be a button issue over in libcosmic / iced? Or should this only be solved here?

**Comment by wash2** [comment]
Thanks for catching this issue. I believe it's a problem with the `ApplicationButton` and `GroupButton` introduced by the app library in its own event handling.

**Comment by wash2** [comment]
Hmm actually the group button seems to handle the Enter key fine
